[mypy]
mypy_path = typings:src
namespace_packages = True
exclude = vendor/
#check_untyped_defs = True
#disallow_untyped_calls = True
#disallow_untyped_defs = True
#disallow_incomplete_defs = True

[mypy-nexyhub_ble.*]
ignore_missing_imports = True

[mypy-bless.*]
ignore_missing_imports = True

[mypy-gpiod.*]
ignore_missing_imports = True