class BlobClient:
    @classmethod
    def from_blob_url(cls, blob_url: str) -> "BlobClient": ...
    def upload_blob(self, data: bytes, overwrite: bool = ...) -> None: ...
    def download_blob(self) -> "StorageStreamDownloader": ...


class StorageStreamDownloader:
    def readall(self) -> bytes: ...
